---
name: Eden
on:
  pull_request:
    branches: [ master ]

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
      - name: setup
        run: |
          sudo apt update
          sudo apt install -y qemu-utils qemu-system-x86
      - name: get eden
        uses: actions/checkout@v2
        with:
          repository: 'itmo-eve/eden'
          ref: 'info-and-console-artifacts'
      - name: build eden
        run: |
          make clean
          make V=1 build
          make V=1 build-tests
      - name: get eve
        uses: actions/checkout@v2
        with:
          path: 'eve'
      - name: fetch or build eve
        env:
          TAG: pr${{ github.event.pull_request.number }}
          CACHE: evebuild/danger
        run: |
          if docker pull "$CACHE:$TAG-kvm"; then
             docker tag  "$CACHE:$TAG-kvm" "lfedge/eve:$TAG-kvm"
             docker tag  "$CACHE:$TAG-kvm" "lfedge/eve:$TAG-kvm-amd64"
          else
             make -C eve V=1 pkgs
             make -C eve V=1 ROOTFS_VERSION="$TAG" HV=kvm eve
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: run
        run: |
          ./eden config add default
          ./eden config set default --key eve.tag --value="$TAG"
          ./eden config set default --key=eve.accel --value=false
          EDITOR=cat ./eden config edit default
          echo > tests/workflow/testdata/eden_stop.txt
          ./eden setup
          ./eden start
          ./eden eve onboard
          ./eden test tests/network -e network_test
      - name: Collect logs
        if: ${{ always() }}
        run: |
          ./eden log --format json > trace.log
          ./eden info > info.log
          cp dist/default-eve.log console.log
          docker logs eden_adam > adam.log 2>&1
      - name: Store raw test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: 'eden-report'
          path: |
            ${{ github.workspace }}/trace.log
            ${{ github.workspace }}/info.log
            ${{ github.workspace }}/console.log
            ${{ github.workspace }}/adam.log
